# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy image

on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
      docker_image_repo:
        required: false
        type: string
        default: ${{ vars.DOCKER_IMAGE_REPO }}
      docker_image_tag:
        required: true
        type: string
      build_id:
        required: false
        type: string
      deployment_env:
        required: true
        type: string
    secrets:
      gitops_ssh_key:
        required: false

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ inputs.project_id}}/${{ inputs.deployment_env }}

    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: kausaltech/kausal-gitops
          ref: main
          ssh-key: ${{ secrets.gitops_ssh_key }}
          fetch-depth: 0
      - name: Update image information
        run: |
          path="${{ inputs.project_id }}/${{ inputs.deployment_env }}"
          mkdir -p $path
          fn="${path}/version.yaml"
          cat <<EOF > ${fn}
          appVersion: '${{ inputs.build_id }}'
          image:
            repository: ${{ inputs.docker_image_repo }}
            tag: '${{ inputs.docker_image_tag }}'
            pullPolicy: IfNotPresent
          EOF
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${fn}
          git commit -m "Deployment of image ${{ inputs.docker_image_tag }} to ${{ inputs.project_id }}/${{ inputs.deployment_env }} by ${{ github.actor }}"
          git push
